version: '3'
services:
  prometheus:
    image: prometheus/prometheus:v2.34.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - '9090:9090'

  alertmanager:
    image: prometheus/alertmanager:v0.23.0
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - '9093:9093'