global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your_email@gmail.com'
  smtp_auth_username: 'your_email@gmail.com'
  smtp_auth_password: 'your_password'

route:
  receiver: team-a
  group_by: ['alertname']

receivers:
- name: team-a
  email_configs:
  - to: your_email@gmail.com
    from: your_email@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: your_email@gmail.com
    auth_password: your_password